_wandb:
    value:
        cli_version: 0.25.1
        e:
            hl6h6pryzxuzy41gn6d0ibvdh0g6zqyd:
                codePath: training/train_hybrid.py
                codePathLocal: training/train_hybrid.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "103865303040"
                        used: "44251181056"
                email: mdaafi04@gmail.com
                executable: /home/mdaafi04/AI-Based-Image-Authenticity-and-Deepfake-Detection-Tool/venv/bin/python
                git:
                    commit: 130e21abb1a472fd0a7805fecd151a7f16cca357
                    remote: https://github.com/Aafi04/AI-Based-Image-Authenticity-and-Deepfake-Detection-Tool.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-d905204a-3d33-1e4a-e947-fd5731bc536a
                host: deepfake-train
                memory:
                    total: "15710253056"
                os: Linux-6.8.0-1052-gcp-x86_64-with-glibc2.35
                program: /home/mdaafi04/AI-Based-Image-Authenticity-and-Deepfake-Detection-Tool/training/train_hybrid.py
                python: CPython 3.10.12
                root: /home/mdaafi04/AI-Based-Image-Authenticity-and-Deepfake-Detection-Tool
                startedAt: "2026-03-26T14:23:24.303484Z"
                writerId: hl6h6pryzxuzy41gn6d0ibvdh0g6zqyd
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.25.1
            "8":
                - 2
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 32
checkpoint_dir:
    value: checkpoints
data_root:
    value: /home/mdaafi04/data
dataset:
    value: faceforensics
device:
    value: cuda
dropout:
    value: 0.4
img_size:
    value: 224
lr:
    value: 0.0001
max_train_samples:
    value: 20000
max_val_samples:
    value: 5000
num_epochs:
    value: 10
num_workers:
    value: 4
save_every:
    value: 5
